### ISSUE TITLE
Fix read order error in reader.py for export

### ISSUE THREAD

**Issue by pablogago11** [AIT-Assistive-Autonomous-Systems/ros2bag_tools#28]
Hi all,

Great work your rosbag tools! Used your package to export the Point Clouds from a rosbag to PCD files and found a bug related to the `set_read_order()` function inside `reader.py` ([line 75](https://github.com/AIT-Assistive-Autonomous-Systems/ros2bag_tools/blob/f1ab11da30528ee615f888a4042861b4594e2132/ros2bag_tools/ros2bag_tools/reader.py#L74C22-L74C22))

I think it all comes from this [fix #1177](https://github.com/ros2/rosbag2/pull/1177#issue-1460938676) from the rosbag2 repository. There was a thrown error: `read order can only be set after open()` related to what they comment on the issue so my solution was to just comment the whole `if` loop (line 74 to 76) and your tool perfectly worked!

Best!

**Comment by devrite** [comment]
Hi pablo,

right, had no time to fix it yet and upon implementation read order was not released yet. Happy to review a pull request, should you have time todo it before me.

BR,

Markus
