### ISSUE TITLE
Could someone please teach me how to use it?

### ISSUE THREAD

**Issue by umsh315** [AIT-Assistive-Autonomous-Systems/ros2bag_tools#37]
Hello, and thank you for providing this wonderful tool.

I do not have any experience with Python or ROS2, and I am struggling with the task of converting LiDAR data recorded in a ros2bag file (.db3) into common point cloud data formats such as .pcd or .ply.

I found this tool highly recommended on various sites and would like to use it, but I am not sure how to proceed. Could someone please provide me with the steps to use it?

My environment is ROS2 Humble, and I have a .db3 file with the recorded LiDAR topic.

**Comment by devrite** [comment]
Just for reference for others. There is a pcd exporter. You will need to set the bag format and check the pcd exporter if it exports everything you need. Currently, there is no LIDAR Range message or image exporter. So PCL messages only.

Note: I have seen that there are forks, which changed some parts of the PCL exporter but did not look into those nor has there been a PR yet. So in case there is something wrong maybe check those changes and get back to us.

**Comment by umsh315** [comment]
Thank you! I was able to convert the topics received from the LiDAR into .pcd format using your tool. I really appreciate it! I had been struggling with handling rosbag for a long time, so this was a big help.
